version: "3"

services:
  nginx:
    container_name: see-skin-prod-nginx
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    container_name: see-skin-prod-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post

  backend:
    container_name: see-skin-prod-backend
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production

  frontend:
    container_name: see-skin-prod-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
