version: "3"

services:
  nginx:
    container_name: see-skin-dev-nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:14
    container_name: see-skin-dev-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: see-skin-dev-backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      # - ./backend/uploads:/usr/src/app/uploads
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    environment:
      DATABASE_URL: postgresql://post:post@db:5432/post
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: see-skin-dev-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    restart: unless-stopped

volumes:
  dbdata:
