version: "3"

services:
  nginx:
    container_name: see-skin-dev-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend
      - backend
    networks:
      - see-skin-dev

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - see-skin-dev

  backend:
    build: backend
    volumes:
      # - ./backend/uploads:/usr/src/app/uploads
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    environment:
      DATABASE_URL: postgresql://post:post@db:5432/post
      ENDPOINT: ${ENDPOINT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - see-skin-dev

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      ENDPOINT: ${ENDPOINT}
    networks:
      - see-skin-dev

volumes:
  dbdata:

networks:
  see-skin-dev:
