version: "3.8"

name: see-skin-prod

services:
  nginx:
    image: 896896/see-skin:nginx
    container_name: see-skin-prod-nginx
    build:
      context: nginx
      target: production

  db:
    container_name: see-skin-prod-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post

  backend:
    image: 896896/see-skin:backend
    container_name: see-skin-prod-backend
    build:
      context: backend
      target: production
    environment:
      ENDPOINT: http://localhost

  frontend:
    image: 896896/see-skin:frontend
    container_name: see-skin-prod-frontend
    build:
      context: frontend
      target: production
