version: "3"

services:
  #  nginx:
  #    container_name: see-skin-test-nginx
  #    image: nginx
  #    ports:
  #      - 80:80
  #      - 443:443
  #    volumes:
  #      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
  #    depends_on:
  #      #      - frontend
  #      - backend

  db:
    container_name: see-skin-dev-db
    image: postgres:14
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

#  backend:
#    container_name: see-skin-test-backend
#    build:
#      context: backend
#      dockerfile: Dockerfile.test
#    volumes:
#      - ./backend/src:/usr/src/app/src
#      - ./backend/jest.config.js:/usr/src/app/jest.config.js
#      - ./backend/prisma:/usr/src/app/prisma
#    environment:
#      DATABASE_URL: postgresql://post:post@db:5432/post
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#    env_file:
#      - backend/.env
#    depends_on:
#      - db

#  frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile.test
#    volumes:
#      - ./frontend:/usr/src/app
#    networks:
#      - see-skin-dev

volumes:
  dbdata:
