version: "3"

services:
  nginx:
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    ports:
      - "5555:5555"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma

  frontend:
    volumes:
      - ./frontend:/usr/src/app