version: "3"

services:
  nginx:
    #    container_name: see-skin-prod-nginx
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    profiles:
      - disabled

  db:
    container_name: see-skin-test-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    volumes:
      - dbdata-test:/var/lib/postgresql/data

  backend:
    container_name: see-skin-test-backend
    build:
      context: backend
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
    restart: "no"

  frontend:
    container_name: see-skin-test-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: production
    restart: "no"
#    profiles:
#      - disabled

#  frontend:
#    container_name: see-skin-prod-frontend
#    build:
#      context: frontend
#      dockerfile: Dockerfile.prod
#    environment:
#      NODE_ENV: production

volumes:
  dbdata-test:
