version: "3.8"

services:
  nginx:
    container_name: see-skin-dev-nginx
    image: 896896/see-skin:nginx
    build: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:14
    container_name: see-skin-dev-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: see-skin-dev-backend
    image: 896896/see-skin:backend
    build:
      context: backend
      target: development
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://post:post@db:5432/post}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: see-skin-dev-frontend
    image: 896896/see-skin:frontend
    build:
      context: frontend
      target: development
    restart: unless-stopped

volumes:
  dbdata:
