version: "3.8"

name: see-skin-prod

services:
  nginx:
    container_name: see-skin-prod-nginx

  db:
    container_name: see-skin-prod-db
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post

  backend:
    container_name: see-skin-prod-backend
    build:
      context: backend
      target: production
    environment:
      ENDPOINT: http://localhost

  frontend:
    container_name: see-skin-prod-frontend
    build:
      context: frontend
      target: production
