version: "3"

services:
  backend:
    ports:
      - "5555:5555"
    volumes:
      - ./backend/:/usr/src/app/
      - /usr/src/app/node_modules

  frontend:
    volumes:
      - ./frontend:/usr/src/app
