version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    volumes:
      # - ./backend/uploads:/usr/src/app/uploads
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    ports:
      - 9000:9000
    environment:
      DATABASE_URL: postgresql://post:post@db:5432/post
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT}
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
    ports:
      - 3000:3000

volumes:
  dbdata:
