FROM --platform=linux/amd64 node:18

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN npx prisma generate

#CMD npx prisma migrate reset --force && yarn start
CMD npx prisma migrate reset --force && npx cross-env NODE_ENV=test jest
