name: Tests

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Test backend
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml run backend sh -c 'npx prisma migrate reset --force && export NODE_ENV=test && npx jest'

  push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker compose -f docker-compose.yml -f docker-compose.prod.yml push
