name: Tests

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Run containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

      - name: Test backend
        run: docker compose exec backend npx prisma migrate reset --force && npx cross-env NODE_ENV=test jest

      #      - name: Test frontend
      #        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml --profile frontend up --exit-code-from frontend

      - name: Clean up
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml down

  push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker compose -f docker-compose.yml -f docker-compose.prod.yml push
